---
- name: put apt key
  copy:
    src: etc/apt/trusted.gpg.d/rspamd.asc
    dest: /etc/apt/trusted.gpg.d/rspamd.asc

- name: put apt source.list
  template:
    src: etc/apt/sources.list.d/rspamd.list.j2
    dest: /etc/apt/sources.list.d/rspamd.list

- name: install packages
  apt:
    name:
      - rspamd
      - unbound
      - logrotate
    state: latest
    update_cache: yes

- name: put config files
  template:
    src: "{{ item }}"
    dest: "{{ item | regex_replace('^.*\\.\\./templates','') | regex_replace('\\.j2$','') }}"
  with_fileglob:
    - ../templates/etc/rspamd/local.d/*.j2
  notify: restart rspamd

- name: do config test
  shell: rspamadm configtest
  changed_when: False
