---
- name: install packages
  apt:
    name:
      - rspamd
      - unbound
    update_cache: yes

- name: put config files
  template:
    src: "{{ item }}"
    dest: "{{ item | regex_replace('^.*\\.\\./templates','') | regex_replace('\\.j2$','') }}"
  with_fileglob:
    - ../templates/etc/rspamd/local.d/*.j2
  notify: restart rspamd
